### PR TITLE
Cleanup of previousUrl and nextUrl after usage to avoid usage of outdated data in some when going back to first page in multi page mode

### PR DESCRIPTION
**Pull request by akinsella**
I have noticed that when you are in multipage mode, some event are wrongly triggered when going back to first page. For instance, pagebeforeshow is triggered on previous page. When going back to first page, jqm calls pagebeforechange event with a data.toPage object and not with a string. In this case, previousUrl and nextUrl are not updated, and when _processRoutes function is called thoses two variable have outdated data affected with urls of previous transition. Therefore, I tried to fix it by cleaning up previousUrl and nextUrl after usage.
With that change, pagebeforeshow is not called on previous page.

### CODE REVIEW

**Comment by akinsella** [comment]
At least, that change fixed my issue => pagebeforeshow is not called anymore on current page when going back to first page in multi page mode

**Comment by akinsella** [comment]
I also minified the fix with UgligyJS via http://jscompress.com/ . It seems there is not official way to minify js for jqmr in README file.

**Comment by azicchetti** [comment]
Hi,
could you please provide an example? I can't reproduce the problem.

Thank you

**Comment by akinsella** [comment]
Hi,

I made some changes since this afternoon, and I'm note able to reproduce it again even in a simple example ... !?!
But I have, I guess, the root cause without being able to run in the case anymore.

When there is a hash change, you run in method 'handleHashChange'. If the 'to' variable (see above) is setted it will be a string, and your code will run via 'if' branch. If not it goes in the else branch, and then it calls changePage with dom version of $.mobile.firstPage and not with string. 
The case with changePage with $.mobile.firstPage is not correctly managed with jqm.router.
If you manage to go into the else branch, you will be able to reproduce my case.

```
        //if to is defined, load it
        if ( to ) {
            // At this point, 'to' can be one of 3 things, a cached page element from
            // a history stack entry, an id, or site-relative/absolute URL. If 'to' is
            // an id, we need to resolve it against the documentBase, not the location.href,
            // since the hashchange could've been the result of a forward/backward navigation
            // that crosses from an external page/dialog to an internal page/dialog.
            to = ( typeof to === "string" && !path.isPath( to ) ) ? ( path.makeUrlAbsolute( '#' + to, documentBase ) ) : to;
            $.mobile.changePage( to, changePageOptions );
        }   else {
            //there's no hash, go to the first page in the dom
            $.mobile.changePage( $.mobile.firstPage, changePageOptions );
```

**Comment by azicchetti** [comment]
I understand, this problem was also reported today by another user:  https://github.com/azicchetti/jquerymobile-router/issues/24

To reproduce the issue, I have to manually change the hash to something like: testPage.html#
Doing this, jqm goes into the "else" branch you mentioned.
The problem also arises when you call changePage programmatically with a page selector, as in: 

$.mobile.changePage( $("#index") );

I think the best way to handle this scenario is invoking the router on the dataUrl property of the page objects that might be passed to changePage.

Give me a little time to find a proper solution for this enhancement.

**Pull request closed without merging**
