### PR TITLE
Fixing issue #73: debugging snippet gets in the way

### PR DESCRIPTION
**Pull request by mzedeler**
Two notes:
- I am just starting to test this now, so this pull request is sent in order to get a code review.
- I have added the option to specify `debugHandler: null` in order to disable debugging entirely. It is an odd way of doing so, but will preserve backwards compatibility.

### CODE REVIEW

**Comment by mzedeler** [comment]
Sorry. This is horribly broken. Will do another.

**Comment by mzedeler** [comment]
This should be it.

I have removed the `debug` function and made it a method on the router prototype. Tested all three cases:
- Using `console.log` (default).
- Using a custom handler (just try `function(err){throw err}` for kicks).
- Debugging disabled.

The first method above may still fail on some browsers, but it shouldn't be any worse that before.

**Comment by azicchetti** [comment]
Thank you, your patch has been merged in the latest commit.
I've just changed the value to disable debugging, since `false` seems easier to remember than `null`.

Thanks again for putting your time into this.

**Comment by mzedeler** [comment]
Sure. No problem. I had an itch...

**Pull request closed without merging**
